repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace   # Removes extra spaces at end of lines
      - id: end-of-file-fixer     # Ensures file ends with a newline
      - id: check-yaml            # Checks if YAML files are valid

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
